name: Validar HTML

on:
  push:
  pull_request:

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Validar tarea3a
        run: npx --yes html-validate tarea3a.html
        name: Validar tarea3b
        run: npx --yes html-validate tarea3b.html
        name: Validar tarea4
        run: npx --yes html-validate tarea4.html
        name: Validar tarea5
        run: npx --yes html-validate tarea5.html
        